### PR TITLE
Remove Symfony5 deprecations

### PR DESCRIPTION
**Pull request by tdutrion**
Non breaking changes to remove symfony5 deprecation logs.

image

### CODE REVIEW

**Comment by yoanm** [comment]
Hello, 

Thanks for your PR 👍 

Unfortunately, this change breaks Symfony 3 compatibility 😞
What was your point exactly, just removing deprecations log or you need Symfony 5 compatibilty ?

**Comment by tdutrion** [comment]
I'm trying to achieve full SF5 support indeed.

Took the solution from https://github.com/doctrine/DoctrineMigrationsBundle/blob/master/DependencyInjection/Configuration.php#L36 and updated my PR.

**Comment by yoanm** [comment]
Ok, at least one more modification will be required : Adding SF5 builds on travis to ensure everything is working well.

IMO, the best move is to remove SF3 compatibility and add SF5 instead. It will be easier (no more `if` required for instance, not too much builds on travis) => `v2.X` will remain for SF3/SF4 compatibility, and `v3.X` will be compatible only with SF4/SF5.

I'm a quite busy currently, and I don't think I will have time to perform that change. 
But I will be more than happy to review your PR in case you have time to do that.

In that case, could you please follow contributing guidelines : 
 - Use your fork to update the code (pull this dedicated branch : https://github.com/yoanm/symfony-jsonrpc-http-server/tree/feature/sf5)
 - Create a PR between your fork and `feature/sf5` branch from this repository

**Comment by yoanm** [comment]
Hello @tdutrion,

Did you start something regarding this PR ? 
I will probably have some spare hours this week-end and could manage the update (at least start to).

**Comment by yoanm** [comment]
Replaced by #48

**Pull request closed without merging**
